# Generated by Django 2.2.16 on 2020-09-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200921_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sdrgadrtgwgs',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
