# Generated by Django 2.2.16 on 2020-09-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200921_0652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hmhgfhgf',
            old_name='wrewtqwe',
            new_name='wrewtqwewetq43tq45trtwertwertwertwertertwe',
        ),
    ]
